## Have total emissions from PM2.5 decreased in the Baltimore City, Maryland (fips == "24510") 
## from 1999 to 2008? Use the base plotting system to make a plot answering this question.
NEI <- readRDS("summarySCC_PM25.rds")
#SCC <- readRDS("Source_Classification_Code.rds")
#NEI<-transform(NEI, year = factor(year))
NEI<-subset(NEI,year >= "1999" & year<= "2008" & fips == "24510", select=c("year","Emissions"))
library(reshape2)
#NEI <- melt(NEI, id=c("year"), measure.vars=c("Emissions"))
tbl <- aggregate(NEI$Emissions, by=list(NEI$year), FUN="sum", na.rm=TRUE)
rm(NEI)
plot(tbl$Group.1,tbl$x,type="n",xlab="Year",ylab="Emissions (Baltimore City)")
lines(tbl$Group.1,tbl$x)
dev.copy(png, file ="plot2.png")
dev.off()
